add testing for ruby 2.3 && 2.4; dropping support for 1.9
sensu-plugins/sensu-plugins-apache pull request #5
Opened 2017-07-01 21:27 UTC by majormoses

other misc changes. 

https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/27

Signed-off-by: Ben Abrams <me@benabrams.it>

2017-07-05 04:39 UTC, eheydrick requested changes

2017-07-05 04:39 UTC, eheydrick commented on CHANGELOG.md
>  ## [Unreleased][unreleased]
Get rid of the second `[unreleased]`.

2017-07-05 04:39 UTC, eheydrick commented on CHANGELOG.md
> +[unreleased]: https://github.com/sensu-plugins/sensu-plugins-apache/compare/1.0.0...HEAD
Capitalize unreleased to be consistent w/ other plugins.

2017-07-05 04:39 UTC, eheydrick commented on sensu-plugins-apache.gemspec
>    # s.cert_chain             = ['certs/sensu-plugins.pem']
get rid of commented out cert junk.

2017-07-05 04:39 UTC, eheydrick commented on sensu-plugins-apache.gemspec
>    # s.signing_key            = File.expand_path(pvt_key) if $PROGRAM_NAME =~ /gem\z/
ditto.

2017-07-05 04:39 UTC, eheydrick commented on Rakefile
> +# frozen_string_literal: true
Is this from rubocop? Looks like a good thing, we should add it to the skel if we're going to do it to all repos.

2017-07-05 05:54 UTC, majormoses commented on Rakefile
> +# frozen_string_literal: true
ya its updated in the skel I think, pretty sure I upgraded all the rubocop stuff recently.

2017-07-05 05:58 UTC, majormoses commented
@eheydrick updated

2017-07-07 07:49 UTC, majormoses commented on Rakefile
> +# frozen_string_literal: true
ya I found it: https://github.com/sensu-plugins/sensu-plugins-skel/pull/2

2017-07-11 02:51 UTC, eheydrick approved these changes

2017-07-11 02:52 UTC, eheydrick commented
👍

2017-07-11 02:52 UTC, merged

2017-07-11 03:27 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-apache/versions/1.0.0